### ISSUE TITLE
Rule CC fails with AttributeError

### ISSUE THREAD

**Issue by yuanshunyue** [WagnerGroup/Energy-Entropy#6]
The rule CC used to work well, but it failed in recent calculations and reported an AttributeError about line 215 in functions.py: 'NoneType' object has no attribute 'write'. A possible reason might be the updated algorithm for its input, mf.chk.

**Comment by lkwagner** [comment]
That should be working with the latest push an hour ago. Can you try it again with this? There were some changes in the pyscf code base.

**Comment by yuanshunyue** [comment]
Sorry! Just noticed the latest push. It works now!

**Comment by lkwagner** [comment]
Great!
